import { NgModule }        from '@angular/core';
import { CommonModule }    from '@angular/common';
import { RouterModule }    from '@angular/router';
import {
  LucideDynamicIcon,
  provideLucideIcons,
  LucideLandmark,
  LucideCamera,
  LucideLayoutDashboard,
  LucideFiles,
  LucideDownload,
  LucideUpload,
  LucideListTree,
  LucideLayers,
  LucideFileInput,
  LucideHandCoins,
  LucideArrowLeftRight,
  LucidePercent,
  LucideCalendarRange,
  LucideReceiptText,
  LucideBarChart3,
  LucideLock,
  LucideUsers,
  LucideBuilding2,
  LucideSettings,
  LucideActivity,
  LucideLogOut,
  LucideChevronDown,
  LucideChevronRight,
  LucidePanelLeft,
  LucidePanelLeftClose,
  LucideBell,
} from '@lucide/angular';
import { SidebarComponent } from './sidebar/sidebar.component';
import { NotificationBellComponent } from './notification-bell/notification-bell.component';

@NgModule({
  declarations: [SidebarComponent, NotificationBellComponent],
  imports:      [CommonModule, RouterModule, LucideDynamicIcon],
  providers:    [provideLucideIcons(
    LucideLandmark,
    LucideCamera,
    LucideLayoutDashboard,
    LucideFiles,
    LucideDownload,
    LucideUpload,
    LucideListTree,
    LucideLayers,
    LucideFileInput,
    LucideHandCoins,
    LucideArrowLeftRight,
    LucidePercent,
    LucideCalendarRange,
    LucideReceiptText,
    LucideBarChart3,
    LucideLock,
    LucideUsers,
    LucideBuilding2,
    LucideSettings,
    LucideActivity,
    LucideLogOut,
    LucideChevronDown,
    LucideChevronRight,
    LucidePanelLeft,
    LucidePanelLeftClose,
    LucideBell,
  )],
  exports:      [SidebarComponent, NotificationBellComponent],
})
export class LayoutModule {}
